#!/bin/sh
# Remise à zéro de l'arborescence de construction (garde config/ et le cache des paquets).
set -e
lb clean noauto "${@}"
rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
